package ru.ls.qa.school.addressbook.tests;// Generated by Selenium IDE

import org.junit.jupiter.api.Test;
import ru.ls.qa.school.addressbook.model.ContactData;

public class NewContactCreationTest extends TestBase {

  @Test
  public void newContactCreation() {
    app.getGroupHelper().createNewContact();
    app.getGroupHelper().addPersonalData(new ContactData("Ivan", "Ivanov", "Ivanovich"));
    app.getGroupHelper().addNickname("Iva");
    app.getGroupHelper().addWorkCompany("LigaStavok");
    app.getGroupHelper().addResidentialAddress("dom pushkina ");
    app.getGroupHelper().saveData();
  }

}
