package ru.ls.qa.school.addressbook.tests;// Generated by Selenium IDE

import org.junit.jupiter.api.Test;
import ru.ls.qa.school.addressbook.model.ContactData;

public class NewContactCreationTest extends TestBase {
  private String firstName = "Ivan";
  private String lastName = "Ivanov";
  private String middleName = "Ivanovich";
  private String nickname = "Iva";
  private String company = "LigaStavok";
  private String address = "dom pushkina";

  @Test
  public void newContactCreation() {
    app.getGroupHelper().createNewContact();
    app.getGroupHelper().getContactHelper().addPersonalData(new ContactData(firstName, lastName, middleName));
    app.getGroupHelper().addNickname(nickname);
    app.getGroupHelper().addWorkCompany(company);
    app.getGroupHelper().addResidentialAddress(address);
    app.getGroupHelper().saveData();
  }
}
