package ru.ls.qa.school.addressbook.tests;// Generated by Selenium IDE

import org.junit.jupiter.api.Test;
import ru.ls.qa.school.addressbook.model.ContactData;

public class NewContactCreationTest extends TestBase {

  private final ContactData contact = new ContactData("Ivan",
                                                      "Ivanov",
                                                      "Ivanovich",
                                                      "Iva",
                                                      "LigaStavok",
                                                      "dom pushkina");

  @Test
  public void newContactCreation() {
    app.getGroupHelper().createNewContact();

    app.getGroupHelper()
       .getContactHelper()
       .addPersonalData(contact);

    app.getGroupHelper().saveData();
  }
}
