package ru.ls.qa.school.addressbook;// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;

public class GroupCreationTests {
  private WebDriver wd;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    wd = new ChromeDriver();
    js = (JavascriptExecutor) wd;
    wd.get("http://localhost:8080/addressbook/");
    login("admin", "secret");
  }

  private void login(String userName, String password) {
    wd.manage().window().setSize(new Dimension(1536, 816));
    wd.findElement(By.name("user")).sendKeys(userName);
    wd.findElement(By.name("pass")).click();
    wd.findElement(By.name("pass")).sendKeys(password);
    wd.findElement(By.cssSelector("input:nth-child(7)")).click();
  }

  @After
  public void tearDown() {
    logoutSite();
    wd.quit();
  }

  private void logoutSite() {
    wd.findElement(By.linkText("Logout")).click();
  }

  @Test
  public void groupCreationTests() {
    goToGroupPage();
    initGroupCreation();
    fillGroupForm("test1", "test2", "test3");
    submitGroupCreation();
    returneToGroupPage();
  }

  private void returneToGroupPage() {
    wd.findElement(By.linkText("group page")).click();
  }

  private void submitGroupCreation() {
    wd.findElement(By.name("submit")).click();
  }

  private void fillGroupForm(String name, String header, String footer) {
    wd.findElement(By.name("group_name")).click();
    wd.findElement(By.name("group_name")).sendKeys(name);
    wd.findElement(By.name("group_header")).click();
    wd.findElement(By.name("group_header")).sendKeys(header);
    wd.findElement(By.name("group_footer")).click();
    wd.findElement(By.name("group_footer")).sendKeys(footer);
  }

  private void initGroupCreation() {
    wd.findElement(By.name("new")).click();
  }

  private void goToGroupPage() {
    wd.findElement(By.linkText("groups")).click();
  }
}
