package ru.ls.qa.school.addressbook;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;

public class NewContactCreationTest {
  private WebDriver wd;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    wd = new ChromeDriver();
    js = (JavascriptExecutor) wd;
    wd.get("http://localhost:8080/addressbook/group.php");
    wd.manage().window().setSize(new Dimension(1536, 816));
    login("admin", "secret");
  }

  private void login(String userName, String password) {
    wd.findElement(By.name("user")).sendKeys(userName);
    wd.findElement(By.name("pass")).click();
    wd.findElement(By.name("pass")).sendKeys(password);
    wd.findElement(By.cssSelector("input:nth-child(7)")).click();
  }

  @After
  public void tearDown() {
    wd.quit();}

  @Test
  public void newContactCreation() {
    createNewContact();
    addPersonalData("Ivan", "Ivanov", "Ivanovich");
    addNickname("Iva");
    addWorkCompany("LigaStavok");
    addResidentialAddress("dom pushkina ");
    saveData();
  }

  private void saveData() {
    wd.findElement(By.cssSelector("input:nth-child(87)")).click();
  }

  private void addResidentialAddress(String address) {
    wd.findElement(By.name("address")).click();
    wd.findElement(By.name("address")).sendKeys(address);
  }

  private void addWorkCompany(String company) {
    wd.findElement(By.name("company")).click();
    wd.findElement(By.name("company")).sendKeys(company);
  }

  private void addNickname(String nickname) {
    wd.findElement(By.name("nickname")).click();
    wd.findElement(By.name("nickname")).sendKeys(nickname);
  }

  private void addPersonalData(String firstname, String middlename, String lastname) {
    wd.findElement(By.name("firstname")).click();
    wd.findElement(By.name("firstname")).sendKeys(firstname);
    wd.findElement(By.name("middlename")).click();
    wd.findElement(By.name("middlename")).sendKeys(middlename);
    wd.findElement(By.name("lastname")).click();
    wd.findElement(By.name("lastname")).sendKeys(lastname);
  }

  private void createNewContact() {
    wd.findElement(By.linkText("add new")).click();
  }
}
